Routerapp::Application.routes.draw do
  get "installed" => "plugins#installed"
  get "message" => "routers#show"
  post "ping" => "routers#ping"
  get "/ping/:gw_mac" => "node_mcus#ping"
  get "/show/:gw_mac" => "node_mcus#show"
  get "/:gw_mac/detail" => "node_mcus#detail"
  post "/xbee" => "xbee#status"
  post "/detail" => "xbee#detail"
  get "/xbee_detail" => "xbee#all_detail"
  get "/sample" => "node_mcus#sample"
  post "renew" => "routers#renew"
  post "installing" => "plugins#installing"
  post "uninstalling" => "plugins#uninstalling"
  post "checkpstatus" => "plugins#checkpstatus"
  post "boot" => "plugins#boot"
  get "checkstat" => "routers#checkstat"
  post "removeing" => "plugins#uninstalling"
  get "login_session" => "routers#create_login_session"
  post "publishcmd" => "routers#pub_cmd"
  resources :plugins
end
